### ISSUE TITLE
Cannot build world using qcom/kirkstone branch

### ISSUE THREAD

**Issue by dougcooper** [96boards/oe-rpb-manifest#171]
Ultimately I am trying to build the esdk with `SDK_INCLUDE_PKGDATA = "1"` and got some missing dependency issues so then i decided to `bitbake world` and see what happens. The following is an example of my first error which is fundamental to oe-rpb. 

```
/ganglia/ganglia_3.6.0.bb DEPENDS on or otherwise requires it)
python was skipped: Recipe will be skipped because: python2 is out of support for long time, read https://www.python.org/doc/sunset-python-2/ https://python3statement.org/ and if you really have to temporarily use this, then set I_SWEAR_TO_MIGRATE_TO_PYTHON3 to "yes"
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'ganglia', 'python']
```

the only workaround i can think of is to create a bbappend for each package that has an issue and add `EXCLUDE_FROM_WORLD = 1`

**Comment by lumag** [comment]
@dougcooper 
Thanks for the report. The `qcom/kirkstone` branch should now be building properly.
BTW: could you please lightly describe your usecase for the RPB? Lately we thought that it is only used by the Qualcomm community and even had thoughts about migrating from it completely.
