### ISSUE TITLE
Build failure - unable to find Kernel revision

### ISSUE THREAD

**Issue by kuscsik** [96boards/oe-rpb-manifest#33]
Hi,

I tried to build the jethro branch.  Configuration

    MACHINE = hikey
    SDKMACHINE = x86_64
    DISTRO = rpb-wayland

It fails with the following error:

NOTE: Running task 886 of 3561 (ID: 50, /home/zoltan.kuscsik/rpb/build-rpb-wayland/conf/../../layers/meta-96boards/recipes-kernel/linux/linux-96boards_4.4.bb, do_fetch)
NOTE: recipe linux-96boards-4.4.11+git-r0: task do_fetch: Started
WARNING: Failed to fetch URL git://github.com/96boards/linux.git;protocol=https;branch=96b/releases/2016.06;name=kernel, attempting MIRRORS if available
ERROR: Fetcher failure: Unable to find revision 78f9b1f7f80a0f7de88f556739333e4ac1ec5945 in branch 96b/releases/2016.06 even from upstream
ERROR: Function failed: Fetcher failure for URL: 'git://github.com/96boards/linux.git;protocol=https;branch=96b/releases/2016.06;name=kernel'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/zoltan.kuscsik/rpb/build-rpb-wayland/tmp-rpb_wayland-glibc/work/hikey-oe-linux/linux-96boards/4.4.11+git-r0/temp/log.do_fetch.16859
NOTE: recipe linux-96boards-4.4.11+git-r0: task do_fetch: Failed
ERROR: Task 50 (/home/zoltan.kuscsik/rpb/build-rpb-wayland/conf/../../layers/meta-96boards/recipes-kernel/linux/linux-96boards_4.4.bb, do_fetch) failed with exit code '1'
NOTE: recipe gcc-cross-aarch64-linaro-5.2-r2015.11-2: task do_compile: Succeeded
NOTE: Tasks Summary: Attempted 887 tasks of which 756 didn't need to be rerun and 1 failed.
NOTE: Writing buildhistory

**Comment by fboudra** [comment]
https://github.com/96boards/meta-96boards/commit/276846fed675b5b8adc157731494f75a30770674
