### ISSUE TITLE
Need support for EULA

### ISSUE THREAD

**Issue by ndechesne** [96boards/oe-rpb-manifest#5]
Some BSP will need EULA to be accepted. the meta-qcom layer for example has it. we need a mechanism to handle that (the QCOM oe-setup script have it already, it needs to be brought into oe-rpb-manifest)

**Comment by twoerner** [comment]
done?

**Comment by ndechesne** [comment]
fixed in f7316fa5d9447ef6cbfa5e690009437f11bcd163
