### ISSUE TITLE
Error rebuilding rpb-console-image from scratch

### ISSUE THREAD

**Issue by ghost** [96boards/oe-rpb-manifest#70]
I am trying to rebuild the rpb console image for the 410c. I started from scratch using repo and am building on Ubuntu 16.04 LTS. I have tried using both the krogoth and morty branches and get the same problem, the log for which I have included below.

DEBUG: Executing python function sstate_task_prefunc
DEBUG: Python function sstate_task_prefunc finished
DEBUG: Executing python function do_package
DEBUG: Executing python function package_get_auto_pr
DEBUG: Python function package_get_auto_pr finished
DEBUG: Executing python function perform_packagecopy
DEBUG: Python function perform_packagecopy finished
DEBUG: Executing python function split_and_strip_files
ERROR: debugsrc symlink fixup failed with exit code 512 (cmd was find /sdd/peter/DB410c/build-rpb/tmp-rpb-glibc/work/aarch64-linaro-linux/nspr/4.12-r0/package/usr/src/debug -type l -print0 -delete | sed s#/sdd/peter/DB410c/build-rpb/tmp-rpb-glibc/work/aarch64-linaro-linux/nspr/4.12-r0/package/usr/src/debug/##g | (cd '/sdd/peter/DB410c/build-rpb/tmp-rpb-glibc/work/aarch64-linaro-linux' ; cpio -pd0mL --no-preserve-owner '/sdd/peter/DB410c/build-rpb/tmp-rpb-glibc/work/aarch64-linaro-linux/nspr/4.12-r0/package/usr/src/debug' 2>/dev/null))
DEBUG: Python function split_and_strip_files finished
DEBUG: Python function do_package finished
ERROR: Function failed: split_and_strip_files

**Comment by lumag** [comment]
Closing, not reproducible, very old
