### ISSUE TITLE
Cannot build rbp-*-image.

### ISSUE THREAD

**Issue by grandpaul** [96boards/oe-rpb-manifest#78]
The openembedded-core seems removed image_types_uboot.bbclass in their commit 65f27122950a35a67ce39ae4cfe93d0dca6b0dab.
It makes the bb which inherits image_types_uboot fail.

**Comment by ndechesne** [comment]
hi,
you're right.. i can see that too:

ERROR: ParseError at /work/oe-rpb-master/build-rpb/conf/../../layers/meta-linaro/meta-linaro/recipes-linaro/images/linaro-image-minimal-initramfs.bb:39: Could not inherit file classes/image_types_uboot.bbclass        | ETA:  0:01:48

@koenkooi do we just need to remove the inherit?

**Comment by ndechesne** [comment]
ping, @koenkooi , @fboudra , master is broken because of this.

**Comment by LoveMeow** [comment]
Is this issue solved? I get the same error ERROR: ParseError at /epositories/poky/meta/classes/image.bbclass:181: Could not inherit file classes/image_types_uboot.bbclass

any hacks how to solve this?

**Comment by ndechesne** [comment]
i think it was fixed with this patch:

https://git.linaro.org/openembedded/meta-linaro.git/commit/meta-linaro/recipes-linaro/images/linaro-image-minimal-initramfs.bb?id=6a7f9b791341592425b7270247e20c4d5f3796a2

**Comment by grandpaul** [comment]
Verified closed. Thanks.
