### ISSUE TITLE
repo init fail

### ISSUE THREAD

**Issue by ghost** [96boards/oe-rpb-manifest#80]
tanureal@tanurealDebian rpb repo init -u https://github.com/96boards/oe-rpb-manifest.git -b morty 
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
remote: Finding sources: 100% (86/86)
remote: Total 86 (delta 40), reused 86 (delta 40)
Unpacking objects: 100% (86/86), done.
From https://gerrit.googlesource.com/git-repo
   c94d6eb..788e962  master     -> origin/master
Get https://github.com/96boards/oe-rpb-manifest.git
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
remote: Counting objects: 887, done.        
remote: Total 887 (delta 0), reused 0 (delta 0), pack-reused 887        
Receiving objects: 100% (887/887), 160.79 KiB | 0 bytes/s, done.
Resolving deltas: 100% (485/485), done.
From https://github.com/96boards/oe-rpb-manifest
 * [new branch]      jethro     -> origin/jethro
 * [new branch]      krogoth    -> origin/krogoth
 * [new branch]      master     -> origin/master
 * [new branch]      morty      -> origin/morty
 * [new branch]      pyro       -> origin/pyro
 * [new branch]      qcom/morty -> origin/qcom/morty
 * [new branch]      release    -> origin/release
 * [new tag]         16.06      -> 16.06
 * [new tag]         16.12      -> 16.12

Your identity is: Lucas Tanure <tanureal@opensource.wolfsonmicro.com>
If you want to change this, please re-run 'repo init' with --config-name

repo has been initialized in /media/workspace/hikey960/rpb

**Comment by jessiepullaro414** [comment]
Hello,

I am not assoicated with 96 boards at all but I am a person that has been working with this a while. This issure looks like a none issue. That is the normal output. This is a really old issue but I was confused by it.

**Comment by ndechesne** [comment]
agreed. this is very old issue. so closing it for now anyways.
