### ISSUE TITLE
Change to meta-browser

### ISSUE THREAD

**Issue by jessiepullaro414** [96boards/oe-rpb-manifest#96]
Hello,

The team that works on the layer meta-browser changed some stuff on master and now this needs meta-rust to build meta-broswer. I ran into this issue while on the pyro branch but seems to be an issue on most of them.

**Comment by ndechesne** [comment]
we fixed it on oe-rpb-manifest/master with https://github.com/96boards/oe-rpb-manifest/commit/d4276d338ba8d31023803b8ff77a7270fff052d2. are you saying this change is needed in other branches from this manifest? 

if so, please submit appropriate PR for review.

**Comment by jessiepullaro414** [comment]
I will do so. Thank you.

**Comment by jessiepullaro414** [comment]
I apologize for reopening this but I have a question before I add my pull request. I see that this is solved 2 diffrent ways. First being just adding the rust layer and the other but doing what was done in morty and changing to this " <project name="OSSystems/meta-browser" path="layers/meta-browser" remote="github" revision="1b4f1e588b1901d8919ea2362b0fcba37c5023e0"/> " which would match your standards?

**Comment by ndechesne** [comment]
well, it's not much up to me, @andrey-konovalov is the one maintaining these bits..

**Comment by jessiepullaro414** [comment]
I will match the standard that they request.
